Refactor ButtonLayout component
SHPEUCF/shpeucfapp pull request #202
Opened 2020-08-24 02:37 UTC by idelmr

## Description

Refactored component and converted to functional component.

## Types of changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other 
Refactoring

## Checklist:

- [x] My code follows the code style of this project found on [Contribution guidelines](https://github.com/SHPEUCF/shpeucfapp/wiki/Contribution-guidelines).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-12-27 21:33 UTC, csepulveda7 requested changes

2020-12-27 21:33 UTC, csepulveda7 commented on src/components/general/ButtonLayout.js
> + * @prop {StyleSheet}  containerStyle  Style for the button children container.
Stylesheet?

2020-12-27 21:33 UTC, csepulveda7 commented on src/components/general/ButtonLayout.js
> + * @desc Component to properly layout multiple buttons as its children.
How many children per button?

2021-01-06 01:28 UTC, esteban737 approved these changes
Looks good to me!

2021-01-06 01:48 UTC, merged