Refactor member redux incuding creating a MemberPanel component for e…
SHPEUCF/shpeucfapp pull request #231
Opened 2021-01-25 01:52 UTC by esteban737

…asy component updating, altering member redux actions to include common functionality, and move firebase calls to member services

Fixes #

## Description

Simplifying member redux by removing unnecessary visitedMember state and saving members in commonly used formats such as sorted alphabetically and sorted by rank. Created MemberPanel component for modular use between different components. Moved firebase calls in members redux to members services.

## Types of changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other  Refactoring

## Checklist:

- [x] My code follows the code style of this project found on [Contribution guidelines](https://github.com/SHPEUCF/shpeucfapp/wiki/Contribution-guidelines).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-01-25 06:08 UTC, idelmr requested changes
Didn't comment on any of the refactoring needed for the member files or any code that was like that before that can improved, e.g.:
* destructuring
* spacing
* unnecessary `return`s
* unnecessary multiline code

2021-01-25 12:34 UTC, esteban737 commented on src/services/members.js
> +		_.orderBy(snapshot.val(), ['lastName', 'firstName'], ['asc', 'asc']).forEach(member => allMemberAccounts[member.id] = member);
They actually do keep they order somehow if you test it. Basically originally I had a sortedIDs array like rankedIDs but I thought about it and I dont think we'd ever really need the original ordering

2021-01-25 22:41 UTC, idelmr commented on src/services/members.js
> +		_.orderBy(snapshot.val(), ['lastName', 'firstName'], ['asc', 'asc']).forEach(member => allMemberAccounts[member.id] = member);
Got it 👍 Although we could probably reduce the code to this. We could remove the `reduce` if it's too much.
```js
const allMemberAccounts = _.orderBy(snapshot.val(), ['lastName', 'firstName'], ['asc', 'asc'])
	.reduce((allMembers, member)) => ({ ...allMembers, [member.id]: member }), {});
let rankedIds = _.orderBy(allMemberAccounts, ['points'], ['desc']).map(({ id }) => id);

for (let pastPoints = 0, pastRank = 1, i = 0; i < rankedIds.length; i++) {
	const { rank, points } = allMemberAccounts[rankedIds[i]];

	pastRank = (points === pastPoints) ? pastRank : (points !== 0) ? i + 1 : rankedIds.length;
	pastPoints = points;
}

resolve({ allMemberAccounts, rankedIds });
```

2021-01-25 23:47 UTC, esteban737 commented on src/services/members.js
> +		_.orderBy(snapshot.val(), ['lastName', 'firstName'], ['asc', 'asc']).forEach(member => allMemberAccounts[member.id] = member);
If you're gonna declare variables in one line in the for loop, you might as well let us declare them in one line anywhere

2021-01-28 19:50 UTC, idelmr approved these changes

2021-01-28 19:51 UTC, merged